# Python 科學計算庫

第一件事情確保我們的庫安裝好了


In [28]:
import numpy as np


In [29]:
array = [1,2,3,4,5]
#array+1

In [32]:
array = np.array([1,2,3,4,5])
type(array)

numpy.ndarray

In [33]:
array2 = array +1
array2

array([2, 3, 4, 5, 6])

In [34]:
array2 + array

array([ 3,  5,  7,  9, 11])

In [35]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [36]:
array.shape

(5,)

In [39]:
tsai_list=[1,2,3,4,5]
#tsai_list.shape

In [38]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])