In [66]:
import numpy as np

In [67]:
tang_list=[1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [68]:
type(tang_array)

numpy.ndarray

In [69]:
tang_array.dtype 
#對於ndarry來說，元素都必須是同樣的型態
#如果不是會自動向下自動轉換

dtype('int32')

In [70]:
tang_array.itemsize 
#查看佔了幾個word

4

In [71]:
tang_array.size
#求元素數量

5

In [72]:
np.size(tang_array)

5

In [73]:
tang_array.shape
#求維度 數量

(5,)

In [74]:
np.shape(tang_array)

(5,)

In [75]:
tang_array.ndim
#求維度

1

In [76]:
tang_array.fill(0)
tang_array

array([0, 0, 0, 0, 0])

### 索引與切片


In [77]:
tang_list=[1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [78]:
tang_array[0]

1

In [79]:
tang_array[-2:]

array([4, 5])

### 矩陣格式(多維的形式)


In [80]:
tang_array = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
tang_array.shape

(3, 3)

In [82]:
tang_array.size

9

In [83]:
tang_array.ndim

2

In [84]:
tang_array[1,1]

5

In [85]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [86]:
tang_array[1]

array([ 4, 10,  6])

In [87]:
tang_array[:,1]

array([ 2, 10,  8])

In [88]:
tang_array[0,0:2]

array([1, 2])

In [89]:
tang_array2 = tang_array #call by ref
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [90]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [91]:
tang_array # call by ref

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [92]:
tang_array2 = tang_array.copy() #call by data 
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [93]:
tang_array2[1,1] = 100000
tang_array2

array([[     1,      2,      3],
       [     4, 100000,      6],
       [     7,      8,      9]])

In [94]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [95]:
tang_array = np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [96]:
mask= np.array([0,0,0,1,1,1,0,0,1,1],dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [97]:
tang_array[mask] #可用一個索引陣列取值

array([30, 40, 50, 80, 90])

In [98]:
random_array = np.random.rand(10)
random_array

array([0.20829949, 0.66102265, 0.43651514, 0.47269678, 0.29893692,
       0.99578332, 0.05641389, 0.73747353, 0.77450384, 0.65045071])

In [99]:
mask = random_array > 0.5
mask

array([False,  True, False, False, False,  True, False,  True,  True,
        True])

In [100]:
tang_array[mask]

array([10, 50, 70, 80, 90])

In [101]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [102]:
np.where(tang_array > 30)
#回傳符合條件的索引

(array([3, 4], dtype=int64),)

In [103]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [104]:
tang_array = np.array([1,2,3,4,5],dtype = np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [105]:
tang_array.dtype

dtype('float32')

In [106]:
tang_array.nbytes

20

In [107]:
tang_array = np.array([1,10,3.5,'str'],dtype=object)
tang_array

array([1, 10, 3.5, 'str'], dtype=object)

In [108]:
tang_array *2 

array([2, 20, 7.0, 'strstr'], dtype=object)

In [109]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [110]:
tang_array

array([1, 2, 3, 4, 5])

In [111]:
tang_array2 = np.asarray(tang_array ,dtype =np.float32)
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [112]:
tang_array

array([1, 2, 3, 4, 5])

In [113]:
tang_array.astype(np.float32) #也可以用此方法 改變型態

array([1., 2., 3., 4., 5.], dtype=float32)