# array數組的數值計算


In [2]:
import numpy as np
tang_array = np.array([[1,2,3],[4,5,6]])
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.sum(tang_array)

21

In [4]:
#指定要執行的操作是沿著哪個軸(維度)
np.sum(tang_array,axis = 0)

array([5, 7, 9])

In [5]:
tang_array.ndim

2

In [6]:
np.sum(tang_array,axis = 1)

array([ 6, 15])

In [7]:
np.sum(tang_array,axis = -1)

array([ 6, 15])

In [8]:
tang_array.sum()

21

In [9]:
tang_array.sum(axis = 0)

array([5, 7, 9])

In [10]:
tang_array.sum(axis = 1)

array([ 6, 15])

In [11]:
tang_array.prod()

720

In [12]:
tang_array.prod(axis = 1)

array([  6, 120])

In [13]:
tang_array.min()

1

In [15]:
tang_array.min(axis = 1)

array([1, 4])

In [16]:
tang_array.argmin() #最小值的索引值

0

In [17]:
tang_array.mean()#取平均值

3.5

In [18]:
tang_array.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [19]:
tang_array.std()

1.707825127659933

In [21]:
tang_array.std(axis = 1)

array([0.81649658, 0.81649658])

In [22]:
tang_array.var() #取變藝術

2.9166666666666665

In [23]:
tang_array.clip(2,4)#比2小用2取代 比4大用4取代

array([[2, 2, 3],
       [4, 4, 4]])

In [24]:
tang_array = np.array([1.2,3.56,6.41])

In [25]:
tang_array.round()

array([1., 4., 6.])

In [26]:
tang_array.round(decimals = 1)

array([1.2, 3.6, 6.4])