### 数组形状操作

In [170]:
import numpy as np
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
tang_array.shape

(10,)

In [172]:
tang_array.shape = 2,5

In [173]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [174]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小必须不能改变

In [175]:
#tang_array.shape = 3,4

In [176]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [177]:
tang_array = tang_array[np.newaxis,:]#增加矩陣維度
tang_array.shape

(1, 10)

In [178]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [179]:
tang_array = tang_array[:,np.newaxis]

tang_array.shape

(10, 1)

In [180]:
tang_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [181]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(10, 1, 1, 1)

In [182]:
tang_array

array([[[[0]]],


       [[[1]]],


       [[[2]]],


       [[[3]]],


       [[[4]]],


       [[[5]]],


       [[[6]]],


       [[[7]]],


       [[[8]]],


       [[[9]]]])

In [183]:
tang_array = tang_array.squeeze()#从数组的形状中删除单维度条目
tang_array.shape

(10,)

In [184]:
tang_array.shape = 2,5

In [185]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [186]:
tang_array.transpose()#transpose 作用是改变序列

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [201]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [188]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组的连接

In [189]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [190]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [191]:
c = np.concatenate((a,b))#串接兩個矩陣
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [192]:
c = np.concatenate((a,b),axis = 0)#讓x軸不變化
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [193]:
c = np.concatenate((a,b),axis = 1)#讓y軸不變
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [194]:
c.shape

(2, 6)

In [195]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [196]:
np.hstack((a,b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

In [197]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [198]:
a.flatten() #拉成一維

array([ 123,  456,  678, 3214,  456,  134])