In [4]:
import numpy as np 
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
tang_array.shape

(10,)

In [6]:
tang_array.shape = 2,5 #改變維度 (1*10) --> (2*5)

In [7]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
# tang_array.shape(3,4) 不能改變元素數量

TypeError: 'tuple' object is not callable

In [ ]:
tang_array.shape

In [11]:
tang_array = tang_array[np.newaxis,:]
tang_array.shape

(1, 1, 2, 5)

In [12]:
tang_array

array([[[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]]])

In [13]:
tang_array = tang_array[:,np.newaxis,np.newaxis]

In [14]:
tang_array

array([[[[[[0, 1, 2, 3, 4],
           [5, 6, 7, 8, 9]]]]]])

In [15]:
tang_array.squeeze()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
tang_array.shape = 2,5
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
tang_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [19]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
a = np.array(([123,456,789],[3214,456,134]))
a

array([[ 123,  456,  789],
       [3214,  456,  134]])

In [24]:
b = np.array(([1235,3124,432],[43,131,134]))
b

array([[1235, 3124,  432],
       [  43,  131,  134]])

In [27]:
c = np.concatenate((a,b)) #記得以數組方式寫格式
c

array([[ 123,  456,  789],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,  131,  134]])

In [28]:
c = np.concatenate((a,b),axis=0) #記得以數組方式寫格式
c

array([[ 123,  456,  789],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,  131,  134]])

In [29]:
c = np.concatenate((a,b),axis=1) #加在另一個維度
c

array([[ 123,  456,  789, 1235, 3124,  432],
       [3214,  456,  134,   43,  131,  134]])

In [30]:
c.shape

(2, 6)

In [31]:
np.vstack((a,b))

array([[ 123,  456,  789],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,  131,  134]])

In [32]:
np.hstack((a,b))

array([[ 123,  456,  789, 1235, 3124,  432],
       [3214,  456,  134,   43,  131,  134]])

In [33]:
a.flatten()

array([ 123,  456,  789, 3214,  456,  134])

In [34]:
b.ravel()

array([1235, 3124,  432,   43,  131,  134])