In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

构造出来一个数组

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.arange(2,20,2,dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [5]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

默认是10为底的

In [24]:
np.logspace(0,1,5)#等比 5等分 10^0~10^2

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [25]:
x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

更常用的 zeros ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones((3,3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [13]:
np.ones((3,3),dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [28]:
a = np.empty(7)
a.shape

(7,)

In [29]:
a

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
a.fill(1) #將所有元素改成 1
a

array([1., 1., 1., 1., 1., 1.])

In [17]:
tang_array = np.array([1,2,3,4])
tang_array

array([1, 2, 3, 4])

In [18]:
np.zeros_like(tang_array)

array([0, 0, 0, 0])

In [19]:
np.ones_like(tang_array)

array([1, 1, 1, 1])

In [27]:
np.identity(9) #單位矩陣

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])