### Numpy的随机模块

In [1]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[0.94572444, 0.63322439],
       [0.45925213, 0.61233704],
       [0.58175503, 0.73780371]])

In [2]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[0, 7, 6, 1],
       [1, 0, 9, 0],
       [7, 2, 6, 6],
       [5, 2, 7, 5],
       [0, 5, 3, 5]])

In [31]:
np.random.rand()
#以给定的形状创建一个数组，并在数组中加入在[0,1]之间均匀分布的随机样本。

0.01525497124633901

In [29]:
np.random.random_sample()
#以给定形状返回[0,1)之间的随机浮点数

0.25242635344484043

In [5]:
np.random.randint(0,10,3)

array([0, 9, 6])

In [6]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)#高斯分布取樣

array([ 0.03983725,  0.04033517, -0.0495036 ,  0.16297665, -0.07491581,
        0.03941924,  0.10567265,  0.05746051, -0.00276247, -0.03739494])

In [7]:
np.set_printoptions(precision = 2)#只打印到小數點第二位

In [8]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.36,  0.19, -0.3 ,  0.16, -0.08, -0.05, -0.22,  0.09, -0.13,
       -0.  ])

### 洗牌

In [9]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(tang_array)

In [11]:
tang_array

array([6, 8, 3, 5, 4, 2, 9, 1, 7, 0])

### 随机的种子

In [12]:
np.random.seed(100)

In [13]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.17,  0.03,  0.12, -0.03,  0.1 ,  0.05,  0.02, -0.11, -0.02,
        0.03])